### ISSUE TITLE
We need a code of conduct

### ISSUE THREAD

**Issue by kennethkalmer** [zadev/code-of-conduct#1]
As our community grows we'll inevitably invite folks in with different points of view than our own, and as we strive for diversity we'll definitely bump heads.

So, we need a code of conduct.

Thanks to @garrensmith for suggesting we build on top of the [CouchDB Code of Conduct](http://couchdb.apache.org/conduct.html).

I can take a stab at converting the document to markdown for publishing here for the time being.

Other suggestions are very welcome.

/cc @zadev/owners

**Comment by garrensmith** [comment]
There is also the [Offline First Code of Conduct](http://offlinefirst.org/coc) that deals specifically with Slack. It also looks excellent.

**Comment by kennethkalmer** [comment]
Oh wow, thanks!

**Comment by gee-forr** [comment]
OK, you can check out #2
