### ISSUE TITLE
invite request form

### ISSUE THREAD

**Issue by larrybotha** [zadev/code-of-conduct#6]
Do you guys have a public invite request form, like [slackin](https://github.com/rauchg/slackin)?

The only place I could find to request an invite was at http://slackchats.hellobox.co/za-developers/2014-12-18, but with only a few requests I'm unsure of its activity.

**Comment by kennethkalmer** [comment]
Hi Larry, we don't have a slackin form. We decided to stick to invite only, and direct messages on Twitter, to keep recruiters out.

I'll get your invite processed, and will chat to @gee-forr about the hellobox site so we can process those requests in a timely manner.

Thanks!

**Comment by larrybotha** [comment]
awesome, thanks :)
